name: Backup main to Google Drive
on: { push: { branches: [ main ] } }
permissions: { contents: read }
jobs:
  backup-to-drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: meta
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          SHORT=$(echo "$BEFORE_SHA" | cut -c1-8)
          DATE=$(date -u +"%Y%m%d-%H%M%S")
          ZIP_NAME="backup-main-${DATE}-${SHORT}.zip"
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
          echo "before_sha=$BEFORE_SHA" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.meta.outputs.before_sha }}
          path: prev
          fetch-depth: 0

      - name: Create ZIP
        run: |
          cd prev
          zip -r "../${{ steps.meta.outputs.zip_name }}" .

      - name: Upload ZIP to Google Drive
        uses: adityak74/google-drive-upload@v1.4
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: ${{ steps.meta.outputs.zip_name }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
